### ISSUE TITLE
Facebook messing up OSB links

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#134]
Say I post on Facebook a link like this https://openstreetbrowser.org/#map=17/-23.54906/-46.63448&categories=memorial.

FB adds a `?fbclid={load_of_trash}` in the link between https://openstreetbrowser.org/ and #map=... , which is not supported by OSB. So everything after https://openstreetbrowser.org/ is dropped.

**Comment by plepe** [comment]
Oh, that's bad. Actually, this serves as compatibility with old links, because you can link to https://openstreetbrowser.org/?map=17/-23.54906/-46.63448 . I'm re-directing from server side code, but unfortunately there is no (direct) way that the server receives parameters after #.

I'm sure, I'll come up with a solution ;-)

**Comment by plepe** [comment]
Sorry, I forgot about this issue.
