### ISSUE TITLE
Translation of "and"

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#49]
Example: [this POI pop-up](https://openstreetbrowser.org/#gastro/n5713651352&map=19/-23.05081/-47.83676&categories=gastro), precisely in "**🍴Cuisine:** `juice` and `fried_food`".

The string "and" is not translatable not only for **Cuisine** but also for any entry with more than 1 value. Both in the POI pop-up and the left side panel.

**Comment by plepe** [comment]
It's true, it was on my internal todo list since I implemented that function :-)

I've been thinking about this for a while - where and how to include this functionality. I made up my mind, it's in the module plepe/modulekit-form. This file in particular: https://github.com/plepe/modulekit-lang/blob/master/lang/fr.json . The important keys are 'enumerate_join' and 'enumerate_last'. See the English file for reference: https://github.com/plepe/modulekit-lang/blob/master/lang/en.json

Make sure to include the spaces!
