### ISSUE TITLE
Pop-up's "Service road attributes" not displaying localized service value

### ISSUE THREAD

**Issue by IgorEliezer** [plepe/OpenStreetBrowser#52]
Example: https://www.openstreetbrowser.org/#railway-infrastructure/w203530982&map=20/-23.04587/-47.83887&categories=railway-infrastructure

In the example's pop-up you'll see `Service road attributes: yard`, but the field for "yard" is shown unlocalized ("yard", "siding", "spur"), even thought they have [their proper translations](https://github.com/plepe/openstreetmap-tag-translations/blob/master/tags/pt-br.json#L716-L718).

----

On an unrelated issue: just noticed `electrified=no` doesn't have a translation entry. I'll add it next time.

**Comment by plepe** [comment]
Good point. Fixed. The usage=* and service=* values are now also included in the description in the list.

Please note, that I changed the translation a bit, the tags `service` and `usage` now always have a `railway=rail` prefix (when used with railway of course): https://github.com/plepe/openstreetmap-tag-translations/blob/543e9c37dc5999d63596308b342ab884a3ae920a/tags/pt-br.json#L716-L727

About the `electrified=no`: it's not necessary to translate, because `no` is translated by `tag:*=no`.

**Comment by IgorEliezer** [comment]
> About the electrified=no: it's not necessary to translate, because no is translated by tag:*=no.

Sorry I should have been specific. In "Railway Electrification" subcategory, the string "not electrified" is not translated on both left panel and pop-up. [Example](https://openstreetbrowser.org/#railway-electrification/w190258751&map=19/-23.04589/-47.83907&categories=railway-electrification).

Also tested on German, Spanish and Russian to be sure.

**Comment by plepe** [comment]
I understand.

I added an extra translation for "tag:electrified=no", which is used by this category from now on: plepe/openstreetmap-tag-translations@b52189e328ccb89a1f3fd50d4e3806d60b835e96

**Comment by plepe** [comment]
Sorry, forgot to update the languages. It's online from now on.
