### ISSUE TITLE
Cache overpass requests?

### ISSUE THREAD

**Issue by joostschouppe** [plepe/OpenStreetBrowser#54]
Two people I sent the link to are getting quota errors for their IP. I'm guessing you use Overpass API and they've asked for too much data through the website. Problem might be that every single move creates a new API call. If there is no easy way to get the number of querys down, you might have to build some sort of serverside caching, like on mapcontrib.xyz or https://ici.brussels/cat:embassy/

**Comment by plepe** [comment]
Yes, these quota errors are cumbersome, but at least querying should work again after a few seconds of waiting.

Serverside caching is not really an option for me, as I don't have a lot of server resources (I paid for a full-blown server for OpenStreetBrowser for several years, but I'm no longer willing to do so). I'm somehow hoping to get a sponsor one day, who is willing to pay for an Overpass server ;-) I'll gladly include a banner on the right sidebar :-)

Another reason is, that the queries are very much optimized, so that they will (almost) never repeat. An option could be to make the query area a bit larger than the view port, so that a small move won't trigger a reload ...

I don't know about mapcontrib.xyz or ici.brussels. Could you point me to information about their caching strategy?

**Comment by plepe** [comment]
As I haven't got any information about caching on the other services, I'm closing the issue.
