### ISSUE TITLE
Hungarian translation ready

### ISSUE THREAD

**Issue by debyos** [plepe/OpenStreetBrowser#58]
Dear All,

I have completed the Hungarian translation but I can't commit it since I am not a programmer "just" a translator. Please put the [attached file](https://github.com/plepe/OpenStreetBrowser/files/2445616/hu.json.zip) to the [right place](https://github.com/plepe/OpenStreetBrowser/blob/master/lang/hu.json).

Thanks in advance

Gábor

**Comment by plepe** [comment]
Sorry, I was very busy over the weekend, that's why I answering only now ...

I'm happy to commit the file myself, but don't you want to try to do it yourself? You just need to click 'edit' (the pencil symbol) on the file in the web browser (https://github.com/plepe/OpenStreetBrowser/blob/master/lang/hu.json). Then it will fork a copy, it will open the file in an editor inside the web browser, you can make any changes and then create a pull request.

You don't need to be a programmer :-)

Stephan. (greetings from Austria)

**Comment by debyos** [comment]
Lieber Stefan,

ich habe es versucht und anscheinend geht es. Und es war tatsächlich nicht
kompliziert, Du bist ein guter Pädagoge. In der Zukunft werde ich
wahrscheinlich auch auf GitHub mutiger, ich habe es sogar auch bei den
Kategorien versucht.

Vielen Dank & tschüß!


Gábor

Stephan Bösch-Plepelits <notifications@github.com> ezt írta (időpont: 2018.
okt. 9., K, 6:13):

**Comment by plepe** [comment]
Sehr gut. Gut, dass ich Dir das gezeigt hab :-)
